package com.exception;

//public class Test6
//{
//	   public static int myMethod()
//	   {
//	       try {
//	            //try block
//	            return 0;
//	       }
//	       finally {
//	            //finally
//	            System.out.println("Inside Finally block");
//	       }
//	  }
//	  public static void main(String args[])
//	  {
//	       System.out.println(Test6.myMethod());
//	  }
//	}





